# -*- coding: utf-8 -*-
"""Paktek Pertemuan 10 - Bab 9 (Pebryan)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqxpnvfB1FGoG5dQOIqzlyV7ek3vJ-v-

### BAB 9 PERTEMUAN 10

---

### 1. Menghitung Jumlah Node pada Binary Tree
"""

class node:
  def __init__(self, data):
    self.data=data
    self.left = None
    self.right = None

def count_nodes(root):
  if root is None:
    return 0

  return 1 + count_nodes(root.left)+count_nodes(root.right)

root = node(10)
root.left=node(5)
root.right=node(15)
root.left.left=node(3)
root.left.right=node(7)
root.left.right.left=node(6)
root.left.right.right=node(8)

print("Jumlah Node = ", count_nodes(root))

"""---

### 2. Traversal Inorder pada Binary Tree
"""

class node:
  def __init__(self, data):
    self.data = data
    self.left = None
    self.right = None

def inorder(root):
  if root :
    inorder(root.left)
    print(root.data, end="")
    inorder(root.right)

root = node("A")
root.left=node("B")
root.right=node("C")
root.left.left=node("D")
root.left.right=node("E")

inorder(root)

"""---

### 3. Menentukan Tinggi (Height) Binary Tree
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

def height(root):
    if root is None:
        return 0

    return 1 + max(height(root.left), height(root.right))

root = Node(1)
root.left = Node(2)
root.right = Node(3)
root.left.left = Node(4)
root.left.right = Node(5)
root.left.left.left = Node(6)

print("Tinggi tree =", height(root))

"""---

### 4. Pencarian Data pada Binary Search Tree (BST)
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

def search(root, key):
    if root is None:
        return False

    if root.data == key:
        return True

    if key < root.data:
        return search(root.left, key)
    else:
        return search(root.right, key)

root = Node(50)
root.left = Node(30)
root.right = Node(70)
root.left.left = Node(20)
root.left.right = Node(40)
root.right.left = Node(60)
root.right.right = Node(80)

key = int(input())

if search(root, key):
    print("Data ditemukan")
else:
    print("Data tidak ditemukan")

"""---

### 5.  Sistem Manajemen Data Mahasiswa Menggunakan Binary Search Tree - Proyek Kompleks
"""

class Node:
    def __init__(self, nim, nama, ipk):
        self.nim = nim
        self.nama = nama
        self.ipk = ipk
        self.left = None
        self.right = None


class BST:
    def __init__(self):
        self.root = None

    def insert(self, root, nim, nama, ipk):
        if root is None:
            return Node(nim, nama, ipk)

        if nim < root.nim:
            root.left = self.insert(root.left, nim, nama, ipk)
        elif nim > root.nim:
            root.right = self.insert(root.right, nim, nama, ipk)

        return root

    def search(self, root, nim):
        if root is None:
            return None

        if root.nim == nim:
            return root

        if nim < root.nim:
            return self.search(root.left, nim)
        else:
            return self.search(root.right, nim)

    def inorder(self, root):
        if root:
            self.inorder(root.left)
            print(f"NIM  : {root.nim}")
            print(f"Nama : {root.nama}")
            print(f"IPK  : {root.ipk}")
            print("-" * 20)
            self.inorder(root.right)

    def min_value(self, node):
        current = node
        while current.left:
            current = current.left
        return current

    def delete(self, root, nim):
        if root is None:
            return root

        if nim < root.nim:
            root.left = self.delete(root.left, nim)

        elif nim > root.nim:
            root.right = self.delete(root.right, nim)

        else:
            # Tidak punya anak
            if root.left is None and root.right is None:
                return None

            # Satu anak
            if root.left is None:
                return root.right

            if root.right is None:
                return root.left

            # Dua anak
            temp = self.min_value(root.right)

            root.nim = temp.nim
            root.nama = temp.nama
            root.ipk = temp.ipk

            root.right = self.delete(root.right, temp.nim)

        return root


bst = BST()

while True:
    print("\n===== MENU =====")
    print("1. Tambah Mahasiswa")
    print("2. Cari Mahasiswa")
    print("3. Tampilkan Mahasiswa")
    print("4. Hapus Mahasiswa")
    print("5. Keluar")

    pilihan = input("Pilihan : ")

    if pilihan == "1":
        nim = int(input("NIM : "))
        nama = input("Nama : ")
        ipk = float(input("IPK : "))

        bst.root = bst.insert(bst.root, nim, nama, ipk)
        print("Data berhasil ditambahkan")

    elif pilihan == "2":
        nim = int(input("Masukkan NIM yang dicari : "))

        data = bst.search(bst.root, nim)

        if data:
            print("\nData ditemukan")
            print("NIM  :", data.nim)
            print("Nama :", data.nama)
            print("IPK  :", data.ipk)
        else:
            print("Data tidak ditemukan")

    elif pilihan == "3":
        if bst.root is None:
            print("Data masih kosong")
        else:
            print("\n=== Data Mahasiswa ===")
            bst.inorder(bst.root)

    elif pilihan == "4":
        nim = int(input("Masukkan NIM yang akan dihapus : "))

        if bst.search(bst.root, nim):
            bst.root = bst.delete(bst.root, nim)
            print("Data berhasil dihapus")
        else:
            print("Data tidak ditemukan")

    elif pilihan == "5":
        print("Program selesai")
        break

    else:
        print("Pilihan tidak valid")