# -*- coding: utf-8 -*-
"""Pertemuan 10 - BAB 9 - Pebryan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xnzP1Wg6qwALTVFIjMe_fRhuSfZieCVP

---

### BinaryTree
"""

# Mengimpor Queue berbasis Linked List
import QueueLinkedList as queue


# Membuat class TreeNode untuk node Binary Tree
class TreeNode:

    # Constructor node
    def __init__(self, data):

        # Menyimpan data node
        self.data = data

        # Anak kiri
        self.leftChild = None

        # Anak kanan
        self.rightChild = None


# Membuat Binary Tree
newBT = TreeNode("Drinks")

# Membuat subtree kiri
leftChild = TreeNode("Hot")
tea = TreeNode("Tea")
coffee = TreeNode("Coffee")

# Menghubungkan node Hot dengan Tea dan Coffee
leftChild.leftChild = tea
leftChild.rightChild = coffee

# Membuat subtree kanan
rightChild = TreeNode("Cold")

# Menghubungkan root dengan child
newBT.leftChild = leftChild
newBT.rightChild = rightChild


# Traversal Preorder
# Root -> Left -> Right
def preOrderTraversal(rootNode):

    # Jika node kosong
    if not rootNode:
        return

    # Cetak root
    print(rootNode.data)

    # Traversal kiri
    preOrderTraversal(rootNode.leftChild)

    # Traversal kanan
    preOrderTraversal(rootNode.rightChild)


# Traversal Inorder
# Left -> Root -> Right
def inOrderTraversal(rootNode):

    if not rootNode:
        return

    # Traversal kiri
    inOrderTraversal(rootNode.leftChild)

    # Cetak root
    print(rootNode.data)

    # Traversal kanan
    inOrderTraversal(rootNode.rightChild)


# Traversal Postorder
# Left -> Right -> Root
def postOrderTraversal(rootNode):

    if not rootNode:
        return

    # Traversal kiri
    postOrderTraversal(rootNode.leftChild)

    # Traversal kanan
    postOrderTraversal(rootNode.rightChild)

    # Cetak root
    print(rootNode.data)


# Traversal Level Order (Breadth First Search)
def levelOrderTraversal(rootNode):

    if not rootNode:
        return

    else:
        # Membuat queue
        customQueue = queue.Queue()

        # Memasukkan root ke queue
        customQueue.enqueue(rootNode)

        while not(customQueue.isEmpty()):

            # Mengambil node terdepan
            root = customQueue.dequeue()

            # Menampilkan data
            print(root.value.data)

            # Menambahkan child kiri ke queue
            if (root.value.leftChild is not None):
                customQueue.enqueue(root.value.leftChild)

            # Menambahkan child kanan ke queue
            if (root.value.rightChild is not None):
                customQueue.enqueue(root.value.rightChild)


# Mencari node dalam Binary Tree
def searchBT(rootNode, nodeValue):

    if not rootNode:
        return "The BT does not exist"

    else:
        customQueue = queue.Queue()
        customQueue.enqueue(rootNode)

        while not(customQueue.isEmpty()):

            root = customQueue.dequeue()

            # Jika data ditemukan
            if root.value.data == nodeValue:
                return "Success"

            # Masukkan child kiri
            if (root.value.leftChild is not None):
                customQueue.enqueue(root.value.leftChild)

            # Masukkan child kanan
            if (root.value.rightChild is not None):
                customQueue.enqueue(root.value.rightChild)

        return "Not found"


# Menambahkan node baru ke Binary Tree
def insertNodeBT(rootNode, newNode):

    if not rootNode:
        rootNode = newNode

    else:
        customQueue = queue.Queue()
        customQueue.enqueue(rootNode)

        while not(customQueue.isEmpty()):

            root = customQueue.dequeue()

            # Jika child kiri ada
            if root.value.leftChild is not None:
                customQueue.enqueue(root.value.leftChild)

            # Jika child kiri kosong
            else:
                root.value.leftChild = newNode
                return "Successfully Inserted"

            # Jika child kanan ada
            if root.value.rightChild is not None:
                customQueue.enqueue(root.value.rightChild)

            # Jika child kanan kosong
            else:
                root.value.rightChild = newNode
                return "Successfully Inserted"


# Mengambil node terdalam (deepest node)
def getDeepestNode(rootNode):

    if not rootNode:
        return

    else:
        customQueue = queue.Queue()
        customQueue.enqueue(rootNode)

        while not(customQueue.isEmpty()):

            root = customQueue.dequeue()

            if (root.value.leftChild is not None):
                customQueue.enqueue(root.value.leftChild)

            if (root.value.rightChild is not None):
                customQueue.enqueue(root.value.rightChild)

        # Node terakhir yang dikunjungi
        deepestNode = root.value

        return deepestNode


# Menghapus node terdalam
def deleteDeepestNode(rootNode, dNode):

    if not rootNode:
        return

    else:
        customQueue = queue.Queue()
        customQueue.enqueue(rootNode)

        while not(customQueue.isEmpty()):

            root = customQueue.dequeue()

            # Jika node ditemukan
            if root.value is dNode:
                root.value = None
                return

            # Periksa child kanan
            if root.value.rightChild:

                if root.value.rightChild is dNode:
                    root.value.rightChild = None
                    return

                else:
                    customQueue.enqueue(root.value.rightChild)

            # Periksa child kiri
            if root.value.leftChild:

                if root.value.leftChild is dNode:
                    root.value.leftChild = None
                    return

                else:
                    customQueue.enqueue(root.value.leftChild)


# Menghapus node tertentu
def deleteNodeBT(rootNode, node):

    if not rootNode:
        return "The BT does not exist"

    else:
        customQueue = queue.Queue()
        customQueue.enqueue(rootNode)

        while not(customQueue.isEmpty()):

            root = customQueue.dequeue()

            # Jika node ditemukan
            if root.value.data == node:

                # Ambil deepest node
                dNode = getDeepestNode(rootNode)

                # Ganti data node dengan deepest node
                root.value.data = dNode.data

                # Hapus deepest node
                deleteDeepestNode(rootNode, dNode)

                return "The node has been successfully deleted"

            if (root.value.leftChild is not None):
                customQueue.enqueue(root.value.leftChild)

            if (root.value.rightChild is not None):
                customQueue.enqueue(root.value.rightChild)

        return "Failed to delete"


# Menghapus seluruh Binary Tree
def deleteBT(rootNode):

    # Menghapus data root
    rootNode.data = None

    # Menghapus child kiri
    rootNode.leftChild = None

    # Menghapus child kanan
    rootNode.rightChild = None

    return "The BT has been successfully deleted"


# Menampilkan Binary Tree dengan Inorder Traversal
inOrderTraversal(newBT)

"""---

### BinaryTreePL
"""

# Membuat Binary Tree menggunakan List (Array Representation)
class BinaryTree:

    # Constructor
    def __init__(self, size):

        # Membuat list dengan ukuran tertentu
        self.customList = size * [None]

        # Menyimpan indeks terakhir yang terisi
        self.lastUsedIndex = 0

        # Menyimpan ukuran maksimum tree
        self.maxSize = size

    # Menambahkan node ke Binary Tree
    def insertNode(self, value):

        # Mengecek apakah tree sudah penuh
        if self.lastUsedIndex + 1 == self.maxSize:
            return "The Binary Tree is full"

        # Menyimpan data pada posisi berikutnya
        self.customList[self.lastUsedIndex + 1] = value

        # Menambah indeks terakhir yang terpakai
        self.lastUsedIndex += 1

        return "The value has been successfully inserted"

    # Mencari node dalam Binary Tree
    def searchNode(self, nodeValue):

        # Menelusuri seluruh list
        for i in range(len(self.customList)):

            # Jika data ditemukan
            if self.customList[i] == nodeValue:
                return "Success"

        return "Not found"

    # Traversal Preorder
    # Root → Left → Right
    def preOrderTraversal(self, index):

        if index > self.lastUsedIndex:
            return

        print(self.customList[index])

        self.preOrderTraversal(index * 2)
        self.preOrderTraversal(index * 2 + 1)

    # Traversal Inorder
    # Left → Root → Right
    def inOrderTraversal(self, index):

        if index > self.lastUsedIndex:
            return

        self.inOrderTraversal(index * 2)

        print(self.customList[index])

        self.inOrderTraversal(index * 2 + 1)

    # Traversal Postorder
    # Left → Right → Root
    def postOrderTraversal(self, index):

        if index > self.lastUsedIndex:
            return

        self.postOrderTraversal(index * 2)
        self.postOrderTraversal(index * 2 + 1)

        print(self.customList[index])

    # Traversal Level Order
    # Menampilkan node sesuai urutan level
    def levelOrderTraversal(self, index):

        for i in range(index, self.lastUsedIndex + 1):
            print(self.customList[i])

    # Menghapus node tertentu
    def deleteNode(self, value):

        # Jika tree kosong
        if self.lastUsedIndex == 0:
            return "There is not any node to delete"

        # Mencari node yang akan dihapus
        for i in range(1, self.lastUsedIndex + 1):

            if self.customList[i] == value:

                # Mengganti node dengan node terakhir
                self.customList[i] = self.customList[self.lastUsedIndex]

                # Menghapus node terakhir
                self.customList[self.lastUsedIndex] = None

                # Mengurangi jumlah node
                self.lastUsedIndex -= 1

                return "The node has been successfully deleted"

    # Menghapus seluruh Binary Tree
    def deleteBT(self):

        # Menghapus list Binary Tree
        self.customList = None

        return "The BT has been successfully deleted"

# Membuat Binary Tree menggunakan List (Array Representation)
class BinaryTree:

    # Constructor
    def __init__(self, size):

        # Membuat list dengan ukuran tertentu
        self.customList = size * [None]

        # Menyimpan indeks terakhir yang terisi
        self.lastUsedIndex = 0

        # Menyimpan ukuran maksimum tree
        self.maxSize = size

    # Menambahkan node ke Binary Tree
    def insertNode(self, value):

        # Mengecek apakah tree sudah penuh
        if self.lastUsedIndex + 1 == self.maxSize:
            return "The Binary Tree is full"

        # Menyimpan data pada posisi berikutnya
        self.customList[self.lastUsedIndex + 1] = value

        # Menambah indeks terakhir yang terpakai
        self.lastUsedIndex += 1

        return "The value has been successfully inserted"

    # Mencari node dalam Binary Tree
    def searchNode(self, nodeValue):

        # Menelusuri seluruh list
        for i in range(len(self.customList)):

            # Jika data ditemukan
            if self.customList[i] == nodeValue:
                return "Success"

        return "Not found"

    # Traversal Preorder
    # Root → Left → Right
    def preOrderTraversal(self, index):

        if index > self.lastUsedIndex:
            return

        print(self.customList[index])

        self.preOrderTraversal(index * 2)
        self.preOrderTraversal(index * 2 + 1)

    # Traversal Inorder
    # Left → Root → Right
    def inOrderTraversal(self, index):

        if index > self.lastUsedIndex:
            return

        self.inOrderTraversal(index * 2)

        print(self.customList[index])

        self.inOrderTraversal(index * 2 + 1)

    # Traversal Postorder
    # Left → Right → Root
    def postOrderTraversal(self, index):

        if index > self.lastUsedIndex:
            return

        self.postOrderTraversal(index * 2)
        self.postOrderTraversal(index * 2 + 1)

        print(self.customList[index])

    # Traversal Level Order
    # Menampilkan node sesuai urutan level
    def levelOrderTraversal(self, index):

        for i in range(index, self.lastUsedIndex + 1):
            print(self.customList[i])

    # Menghapus node tertentu
    def deleteNode(self, value):

        # Jika tree kosong
        if self.lastUsedIndex == 0:
            return "There is not any node to delete"

        # Mencari node yang akan dihapus
        for i in range(1, self.lastUsedIndex + 1):

            if self.customList[i] == value:

                # Mengganti node dengan node terakhir
                self.customList[i] = self.customList[self.lastUsedIndex]

                # Menghapus node terakhir
                self.customList[self.lastUsedIndex] = None

                # Mengurangi jumlah node
                self.lastUsedIndex -= 1

                return "The node has been successfully deleted"

    # Menghapus seluruh Binary Tree
    def deleteBT(self):

        # Menghapus list Binary Tree
        self.customList = None

        return "The BT has been successfully deleted"

# Membuat Binary Tree dengan ukuran 8
newBT = BinaryTree(8)

# Menambahkan node ke Binary Tree
newBT.insertNode("Drinks")
newBT.insertNode("Hot")
newBT.insertNode("Cold")
newBT.insertNode("Tea")
newBT.insertNode("Coffee")

"""---

### QueueLinkedList
"""

# Membuat class Node
# Node digunakan untuk menyimpan data dan alamat node berikutnya
class Node:

    # Constructor Node
    def __init__(self, value=None):

        # Menyimpan nilai/data node
        self.value = value

        # Pointer ke node berikutnya
        self.next = None

    # Mengubah object Node menjadi string
    def __str__(self):
        return str(self.value)


# Membuat class LinkedList
class LinkedList:

    # Constructor LinkedList
    def __init__(self):

        # Node pertama
        self.head = None

        # Node terakhir
        self.tail = None


# Membuat class Queue menggunakan LinkedList
class Queue:

    # Constructor Queue
    def __init__(self):

        # Membuat object LinkedList
        self.linkedList = LinkedList()

    # Menampilkan isi queue
    def __str__(self):

        # Mengubah setiap node menjadi string
        values = [str(x) for x in self.linkedList]

        return ' '.join(values)

    # Menambahkan data ke belakang queue
    def enqueue(self, value):

        # Membuat node baru
        newNode = Node(value)

        # Jika queue kosong
        if self.linkedList.head == None:
            self.linkedList.head = newNode
            self.linkedList.tail = newNode

        # Jika queue sudah memiliki data
        else:
            self.linkedList.tail.next = newNode
            self.linkedList.tail = newNode

    # Mengecek apakah queue kosong
    def isEmpty(self):

        if self.linkedList.head == None:
            return True

        else:
            return False

    # Menghapus data paling depan queue (FIFO)
    def dequeue(self):

        # Jika queue kosong
        if self.isEmpty():
            return "There is not any node in the Queue"

        else:
            # Menyimpan node pertama
            tempNode = self.linkedList.head

            # Jika hanya ada satu node
            if self.linkedList.head == self.linkedList.tail:
                self.linkedList.head = None
                self.linkedList.tail = None

            # Jika ada lebih dari satu node
            else:
                self.linkedList.head = self.linkedList.head.next

            # Mengembalikan node yang dihapus
            return tempNode

    # Melihat data paling depan tanpa menghapus
    def peek(self):

        # Jika queue kosong
        if self.isEmpty():
            return "There is not any node in the Queue"

        else:
            return self.linkedList.head

    # Menghapus seluruh isi queue
    def delete(self):

        self.linkedList.head = None
        self.linkedList.tail = None




# Membuat object Queue
# custQueue = Queue()

# Menambahkan data ke queue
# custQueue.enqueue(1)
# custQueue.enqueue(2)
# custQueue.enqueue(3)

# Menampilkan isi queue
# print(custQueue)

# Menampilkan data paling depan
# print(custQueue.peek())

# Queue tetap sama karena peek tidak menghapus data
# print(custQueue)

"""---

### CreateTree
"""

# Membuat class TreeNode untuk General Tree
class TreeNode:

    # Constructor
    def __init__(self, data, children=[]):

        # Menyimpan data node
        self.data = data

        # Menyimpan daftar child (anak)
        self.children = children

    # Menampilkan struktur tree dalam bentuk hierarki
    def __str__(self, level=0):

        # Memberikan indentasi sesuai level node
        ret = "  " * level + str(self.data) + "\n"

        # Menampilkan seluruh child secara rekursif
        for child in self.children:
            ret += child.__str__(level + 1)

        return ret

    # Menambahkan child ke node saat ini
    def addChild(self, TreeNode):
        self.children.append(TreeNode)

# Membuat root node
tree = TreeNode('Drinks', [])

# Membuat child level 1
cold = TreeNode('Cold', [])
hot = TreeNode('Hot', [])

# Menambahkan Cold dan Hot ke Drinks
tree.addChild(cold)
tree.addChild(hot)

# Membuat child level 2
tea = TreeNode('Tea', [])
coffee = TreeNode('Coffee', [])
cola = TreeNode('Cola', [])
fanta = TreeNode('Fanta', [])

# Menambahkan Cola dan Fanta ke Cold
cold.addChild(cola)
cold.addChild(fanta)

# Menambahkan Tea dan Coffee ke Hot
hot.addChild(tea)
hot.addChild(coffee)

# Menampilkan seluruh struktur tree
print(tree)

"""---

### BST
"""

# Membuat class Node
# Node digunakan untuk menyimpan data dan alamat node berikutnya
class Node:

    # Constructor Node
    def __init__(self, value=None):

        # Menyimpan nilai/data node
        self.value = value

        # Pointer ke node berikutnya
        self.next = None

    # Mengubah object Node menjadi string
    def __str__(self):
        return str(self.value)


# Membuat class LinkedList
class LinkedList:

    # Constructor LinkedList
    def __init__(self):

        # Node pertama
        self.head = None

        # Node terakhir
        self.tail = None


# Membuat class Queue menggunakan LinkedList
class Queue:

    # Constructor Queue
    def __init__(self):

        # Membuat object LinkedList
        self.linkedList = LinkedList()

    # Menampilkan isi queue
    def __str__(self):

        # Mengubah setiap node menjadi string
        values = []
        current = self.linkedList.head
        while current:
            values.append(str(current.value))
            current = current.next
        return ' '.join(values)

    # Menambahkan data ke belakang queue
    def enqueue(self, value):

        # Membuat node baru
        newNode = Node(value)

        # Jika queue kosong
        if self.linkedList.head == None:
            self.linkedList.head = newNode
            self.linkedList.tail = newNode

        # Jika queue sudah memiliki data
        else:
            self.linkedList.tail.next = newNode
            self.linkedList.tail = newNode

    # Mengecek apakah queue kosong
    def isEmpty(self):

        if self.linkedList.head == None:
            return True

        else:
            return False

    # Menghapus data paling depan queue (FIFO)
    def dequeue(self):

        # Jika queue kosong
        if self.isEmpty():
            # Original code returns a string, but it's better to return None or raise an error
            # For consistency with how the original code was handling it, returning a Node with an error message
            # If the consumer expects a Node, this might break, but a more robust Queue would raise an exception.
            # Given the context of `root.value.data` later, `dequeue` should return a `Node` object.
            # Returning `None` is more idiomatic for an empty queue, but the original logic prints `root.value.data`
            # which would fail if root is None. The problem is in the `if self.isEmpty()` for `dequeue`,
            # it returns a string 'There is not any node in the Queue', but the actual usage of `root` later expects a Node object.
            # Let's adjust to return None or handle this more gracefully, but for now, the primary error is `ModuleNotFoundError`.
            # For now, let's assume the calling code in LevelOrderTraversal will not call dequeue on an empty queue.
            return Node("There is not any node in the Queue") # Keeping it consistent with original's return type for `peek`

        else:
            # Menyimpan node pertama
            tempNode = self.linkedList.head

            # Jika hanya ada satu node
            if self.linkedList.head == self.linkedList.tail:
                self.linkedList.head = None
                self.linkedList.tail = None

            # Jika ada lebih dari satu node
            else:
                self.linkedList.head = self.linkedList.head.next

            # Mengembalikan node yang dihapus
            return tempNode

    # Melihat data paling depan tanpa menghapus
    def peek(self):

        # Jika queue kosong
        if self.isEmpty():
            return "There is not any node in the Queue"

        else:
            return self.linkedList.head

    # Menghapus seluruh isi queue
    def delete(self):

        self.linkedList.head = None
        self.linkedList.tail = None


# Membuat class BSTNode (Binary Search Tree Node)
class BSTNode:

    # Constructor
    def __init__(self, data):

        # Menyimpan data node
        self.data = data

        # Anak kiri
        self.leftChild = None

        # Anak kanan
        self.rightChild = None


# Menambahkan node ke BST
def insertNode(rootNode, nodeValue):

    # Jika root masih kosong
    if rootNode.data == None:
        rootNode.data = nodeValue

    # Jika nilai lebih kecil atau sama dengan root
    elif nodeValue <= rootNode.data:

        # Jika child kiri kosong
        if rootNode.leftChild is None:
            rootNode.leftChild = BSTNode(nodeValue)

        # Rekursif ke subtree kiri
        else:
            insertNode(rootNode.leftChild, nodeValue)

    # Jika nilai lebih besar dari root
    else:

        # Jika child kanan kosong
        if rootNode.rightChild is None:
            rootNode.rightChild = BSTNode(nodeValue)

        # Rekursif ke subtree kanan
        else:
            insertNode(rootNode.rightChild, nodeValue)

    return "The node has been successfully inserted"


# Traversal Preorder
# Root -> Left -> Right
def preOrderTraversal(rootNode):

    if not rootNode:
        return

    print(rootNode.data)

    preOrderTraversal(rootNode.leftChild)
    preOrderTraversal(rootNode.rightChild)


# Traversal Inorder
# Left -> Root -> Right
def inOrderTraversal(rootNode):

    if not rootNode:
        return

    inOrderTraversal(rootNode.leftChild)

    print(rootNode.data)

    inOrderTraversal(rootNode.rightChild)


# Traversal Postorder
# Left -> Right -> Root
def postOrderTraversal(rootNode):

    if not rootNode:
        return

    postOrderTraversal(rootNode.leftChild)
    postOrderTraversal(rootNode.rightChild)

    print(rootNode.data)


# Traversal Level Order (BFS)
def levelOrderTraversal(rootNode):

    if not rootNode:
        return

    else:
        # Membuat queue
        customQueue = Queue()

        # Memasukkan root
        customQueue.enqueue(rootNode)

        while not(customQueue.isEmpty()):

            # Mengambil node terdepan
            root = customQueue.dequeue()

            # Check if root is actually a valid Node object with a value
            if isinstance(root, Node) and root.value is not None:
                print(root.value.data)

                # Masukkan child kiri
                if root.value.leftChild is not None:
                    customQueue.enqueue(root.value.leftChild)

                # Masukkan child kanan
                if root.value.rightChild is not None:
                    customQueue.enqueue(root.value.rightChild)


# Mencari node dalam BST
def searchNode(rootNode, nodeValue):

    # Jika data ditemukan di root
    if rootNode.data == nodeValue:
        print("The value is found")

    # Jika nilai lebih kecil
    elif nodeValue < rootNode.data:

        if rootNode.leftChild and rootNode.leftChild.data == nodeValue: # Added check for rootNode.leftChild existence
            print("The value is found")

        elif rootNode.leftChild: # Added check for rootNode.leftChild existence before recursion
            searchNode(rootNode.leftChild, nodeValue)
        else:
            print("The value is not found") # If left child doesn't exist and value not found

    # Jika nilai lebih besar
    else:

        if rootNode.rightChild and rootNode.rightChild.data == nodeValue: # Added check for rootNode.rightChild existence
            print("The value is found")

        elif rootNode.rightChild: # Added check for rootNode.rightChild existence before recursion
            searchNode(rootNode.rightChild, nodeValue)
        else:
            print("The value is not found") # If right child doesn't exist and value not found


# Mencari node dengan nilai terkecil
def minValueNode(bstNode):

    current = bstNode

    # Bergerak terus ke kiri
    while (current.leftChild is not None):
        current = current.leftChild

    return current


# Menghapus node dari BST
def deleteNode(rootNode, nodeValue):

    if rootNode is None:
        return rootNode

    # Cari node di subtree kiri
    if nodeValue < rootNode.data:
        rootNode.leftChild = deleteNode(
            rootNode.leftChild,
            nodeValue
        )

    # Cari node di subtree kanan
    elif nodeValue > rootNode.data:
        rootNode.rightChild = deleteNode(
            rootNode.rightChild,
            nodeValue
        )

    else:

        # Kasus 1: Tidak punya child kiri
        if rootNode.leftChild is None:
            temp = rootNode.rightChild
            rootNode = None
            return temp

        # Kasus 2: Tidak punya child kanan
        if rootNode.rightChild is None:
            temp = rootNode.leftChild
            rootNode = None
            return temp

        # Kasus 3: Memiliki dua child
        temp = minValueNode(rootNode.rightChild)

        # Ganti data dengan inorder successor
        rootNode.data = temp.data

        # Hapus inorder successor
        rootNode.rightChild = deleteNode(
            rootNode.rightChild,
            temp.data
        )

    return rootNode


# Menghapus seluruh BST
def deleteBST(rootNode):

    rootNode.data = None
    rootNode.leftChild = None
    rootNode.rightChild = None

    return "The BST has been successfully deleted"



# Membuat BST kosong
newBST = BSTNode(None)

# Menambahkan node ke BST
insertNode(newBST, 70)
insertNode(newBST, 50)
insertNode(newBST, 90)
insertNode(newBST, 30)
insertNode(newBST, 60)
insertNode(newBST, 80)
insertNode(newBST, 100)
insertNode(newBST, 20)
insertNode(newBST, 40)

# Menghapus seluruh BST
print(deleteBST(newBST))

# Menampilkan BST dengan Level Order Traversal
levelOrderTraversal(newBST)

"""---

### QueueLinkedList
"""

class Node:
    def __init__(self, value=None):
        self.value = value
        self.next = None

    def __str__(self):
        return str(self.value)

class LinkedList:
    def __init__(self):
        self.head = None
        self.tail = None



class Queue:
    def __init__(self):
        self.linkedList = LinkedList()

    def __str__(self):
        values = [str(x) for x in self.linkedList]
        return ' '.join(values)

    def enqueue(self, value):
        newNode = Node(value)
        if self.linkedList.head == None:
            self.linkedList.head = newNode
            self.linkedList.tail = newNode
        else:
            self.linkedList.tail.next = newNode
            self.linkedList.tail = newNode

    def isEmpty(self):
        if self.linkedList.head == None:
            return True
        else:
            return False

    def dequeue(self):
        if self.isEmpty():
            return "There is not any node in the Queue"
        else:
            tempNode = self.linkedList.head
            if self.linkedList.head == self.linkedList.tail:
                self.linkedList.head = None
                self.linkedList.tail = None
            else:
                self.linkedList.head = self.linkedList.head.next
            return tempNode

    def peek(self):
        if self.isEmpty():
            return "There is not any node in the Queue"
        else:
            return self.linkedList.head

    def delete(self):
        self.linkedList.head = None
        self.linkedList.tail = None

# custQueue = Queue()
# custQueue.enqueue(1)
# custQueue.enqueue(2)
# custQueue.enqueue(3)
# print(custQueue)
# print(custQueue.peek())
# print(custQueue)